#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSwaps' function below.
#
# The function accepts INTEGER_ARRAY a as parameter.
#


def countSwaps(a):
    swap_count = 0
    for i in range(len(arr)):
        for j in range(len(arr)-1):
            if arr[j] > arr[j+1]:
                swap_count += 1
                arr[j+1] , arr[j] = arr[j] , arr[j+1]
            
    print("Array is sorted in "+ str(swap_count) +" swaps.")
    print("First Element: " + str(arr[0]))
    print("Last Element: " + str(arr[-1]))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    countSwaps(arr)
